service: covid-19-dashboard
runtime: python37

instance_class: B4_1G

basic_scaling:
    max_instances: 2
    idle_timeout: 20m

resources:
    cpu: 4
    memory_gb: 2
    disk_size_gb: 10

entrypoint: gunicorn -t 0 -b 0.0.0.0:8080 app:server